project:
  type: website

website:
  title: "Naomi Chou"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Experience
      - href: Projects.qmd
        text: Projects
    right: 
      - icon: github
        menu: 
          - text: Website Source Code
            url: https://github.com/naomichou/Naomi-s-Personal-Website
          - text: Github Profile
            url: https://github.com/naomichou
  page-footer:
    right: "&copy; Naomi Chou 2024"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto


